input{
  beats { port=>5044}
  tcp {
    port=>5000
    codec=>line
  }
}


filter{
  if [message]{
    json{
        source=>"message"
        target=>"parsed"
        remove_field=>["message"]
    }
  }

  #nanosecond 제거후 @timestamp 변환
  mutate{
    gsub=>["[parsed][@timestamp]","\.\d{3,9}Z$","Z"]
  }

  date{
    match=>["[parsed][@timestamp]","ISO8601"]
    target=>"@timestamp"
    #remove_field=>["[parsed][@timestamp]"]
  }
}


output{
  elasticsearch{
    hosts=>["http://elasticsearch:9200"]
    index=>"spring-app-%{+YYYY.MM.dd}"

    #중복을 방지하기 위해서 document_id를 부여
    document_id=>"%{[parsed][logger_name]}-%{[parsed][@timestamp]}"
  }

  stdout{codec=>rubydebug}

}



















